Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Internal Server Error: /api/send-mail
Traceback (most recent call last):
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 122, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/middleware/common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/middleware/common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/api/send-mail/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
"POST /api/send-mail HTTP/1.1" 500 82971
DEBUG - En-tête Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1OTY5OTE2LCJpYXQiOjE3NDUzNjUxMTYsImp0aSI6ImViOTBhYmJhNjg0ZTQ5OWI4MTc5ZTJkYjM4YzFiNDY2IiwidXNlcl9pZCI6MX0.UvlkWX10E0-ED0vZAkWhQ_39jimXJauOJylPyiAU9Hc
DEBUG - User authentifié: True
DEBUG - Type d'utilisateur: User
DEBUG - En-tête Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1OTY5OTE2LCJpYXQiOjE3NDUzNjUxMTYsImp0aSI6ImViOTBhYmJhNjg0ZTQ5OWI4MTc5ZTJkYjM4YzFiNDY2IiwidXNlcl9pZCI6MX0.UvlkWX10E0-ED0vZAkWhQ_39jimXJauOJylPyiAU9Hc
DEBUG - User authentifié: True
DEBUG - Type d'utilisateur: User
Internal Server Error: /api/send-mail
Traceback (most recent call last):
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 122, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/middleware/common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/middleware/common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/api/send-mail/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
"POST /api/send-mail HTTP/1.1" 500 82854
DEBUG - En-tête Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1OTY5OTE2LCJpYXQiOjE3NDUzNjUxMTYsImp0aSI6ImViOTBhYmJhNjg0ZTQ5OWI4MTc5ZTJkYjM4YzFiNDY2IiwidXNlcl9pZCI6MX0.UvlkWX10E0-ED0vZAkWhQ_39jimXJauOJylPyiAU9Hc
DEBUG - User authentifié: True
DEBUG - Type d'utilisateur: User
DEBUG - En-tête Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1OTY5OTE2LCJpYXQiOjE3NDUzNjUxMTYsImp0aSI6ImViOTBhYmJhNjg0ZTQ5OWI4MTc5ZTJkYjM4YzFiNDY2IiwidXNlcl9pZCI6MX0.UvlkWX10E0-ED0vZAkWhQ_39jimXJauOJylPyiAU9Hc
DEBUG - User authentifié: True
DEBUG - Type d'utilisateur: User
DEBUG - En-tête Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1OTY5OTE2LCJpYXQiOjE3NDUzNjUxMTYsImp0aSI6ImViOTBhYmJhNjg0ZTQ5OWI4MTc5ZTJkYjM4YzFiNDY2IiwidXNlcl9pZCI6MX0.UvlkWX10E0-ED0vZAkWhQ_39jimXJauOJylPyiAU9Hc
DEBUG - User authentifié: True
DEBUG - Type d'utilisateur: User
DEBUG - En-tête Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1OTY5OTE2LCJpYXQiOjE3NDUzNjUxMTYsImp0aSI6ImViOTBhYmJhNjg0ZTQ5OWI4MTc5ZTJkYjM4YzFiNDY2IiwidXNlcl9pZCI6MX0.UvlkWX10E0-ED0vZAkWhQ_39jimXJauOJylPyiAU9Hc
DEBUG - User authentifié: True
DEBUG - Type d'utilisateur: User
DEBUG - En-tête Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1OTY5OTE2LCJpYXQiOjE3NDUzNjUxMTYsImp0aSI6ImViOTBhYmJhNjg0ZTQ5OWI4MTc5ZTJkYjM4YzFiNDY2IiwidXNlcl9pZCI6MX0.UvlkWX10E0-ED0vZAkWhQ_39jimXJauOJylPyiAU9Hc
DEBUG - User authentifié: True
DEBUG - Type d'utilisateur: User
DEBUG - En-tête Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1OTY5OTE2LCJpYXQiOjE3NDUzNjUxMTYsImp0aSI6ImViOTBhYmJhNjg0ZTQ5OWI4MTc5ZTJkYjM4YzFiNDY2IiwidXNlcl9pZCI6MX0.UvlkWX10E0-ED0vZAkWhQ_39jimXJauOJylPyiAU9Hc
DEBUG - User authentifié: True
DEBUG - Type d'utilisateur: User
DEBUG - En-tête Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1OTY5OTE2LCJpYXQiOjE3NDUzNjUxMTYsImp0aSI6ImViOTBhYmJhNjg0ZTQ5OWI4MTc5ZTJkYjM4YzFiNDY2IiwidXNlcl9pZCI6MX0.UvlkWX10E0-ED0vZAkWhQ_39jimXJauOJylPyiAU9Hc
DEBUG - User authentifié: True
DEBUG - Type d'utilisateur: User
DEBUG - En-tête Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1OTY5OTE2LCJpYXQiOjE3NDUzNjUxMTYsImp0aSI6ImViOTBhYmJhNjg0ZTQ5OWI4MTc5ZTJkYjM4YzFiNDY2IiwidXNlcl9pZCI6MX0.UvlkWX10E0-ED0vZAkWhQ_39jimXJauOJylPyiAU9Hc
DEBUG - User authentifié: True
DEBUG - Type d'utilisateur: User
DEBUG - En-tête Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1OTY5OTE2LCJpYXQiOjE3NDUzNjUxMTYsImp0aSI6ImViOTBhYmJhNjg0ZTQ5OWI4MTc5ZTJkYjM4YzFiNDY2IiwidXNlcl9pZCI6MX0.UvlkWX10E0-ED0vZAkWhQ_39jimXJauOJylPyiAU9Hc
DEBUG - User authentifié: True
DEBUG - Type d'utilisateur: User
DEBUG - En-tête Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1OTY5OTE2LCJpYXQiOjE3NDUzNjUxMTYsImp0aSI6ImViOTBhYmJhNjg0ZTQ5OWI4MTc5ZTJkYjM4YzFiNDY2IiwidXNlcl9pZCI6MX0.UvlkWX10E0-ED0vZAkWhQ_39jimXJauOJylPyiAU9Hc
DEBUG - User authentifié: True
DEBUG - Type d'utilisateur: User
DEBUG - En-tête Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1OTY5OTE2LCJpYXQiOjE3NDUzNjUxMTYsImp0aSI6ImViOTBhYmJhNjg0ZTQ5OWI4MTc5ZTJkYjM4YzFiNDY2IiwidXNlcl9pZCI6MX0.UvlkWX10E0-ED0vZAkWhQ_39jimXJauOJylPyiAU9Hc
DEBUG - User authentifié: True
DEBUG - Type d'utilisateur: User
DEBUG - En-tête Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1OTY5OTE2LCJpYXQiOjE3NDUzNjUxMTYsImp0aSI6ImViOTBhYmJhNjg0ZTQ5OWI4MTc5ZTJkYjM4YzFiNDY2IiwidXNlcl9pZCI6MX0.UvlkWX10E0-ED0vZAkWhQ_39jimXJauOJylPyiAU9Hc
DEBUG - User authentifié: True
DEBUG - Type d'utilisateur: User
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   DEBUG - En-tête Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1OTY5OTE2LCJpYXQiOjE3NDUzNjUxMTYsImp0aSI6ImViOTBhYmJhNjg0ZTQ5OWI4MTc5ZTJkYjM4YzFiNDY2IiwidXNlcl9pZCI6MX0.UvlkWX10E0-ED0vZAkWhQ_39jimXJauOJylPyiAU9Hc
DEBUG - User authentifié: True
DEBUG - Type d'utilisateur: User
DEBUG - En-tête Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1OTY5OTE2LCJpYXQiOjE3NDUzNjUxMTYsImp0aSI6ImViOTBhYmJhNjg0ZTQ5OWI4MTc5ZTJkYjM4YzFiNDY2IiwidXNlcl9pZCI6MX0.UvlkWX10E0-ED0vZAkWhQ_39jimXJauOJylPyiAU9Hc
DEBUG - User authentifié: True
DEBUG - Type d'utilisateur: User
Internal Server Error: /auth/users/
Traceback (most recent call last):
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/utils/module_loading.py", line 16, in cached_import
    return getattr(module, class_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'rest_framework.permissions' has no attribute 'IsAdmin'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/rest_framework/views.py", line 331, in check_permissions
    for permission in self.get_permissions():
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/djoser/views.py", line 73, in get_permissions
    self.permission_classes = settings.PERMISSIONS.user_list
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/djoser/conf.py", line 22, in __getattribute__
    val = [import_string(v) if isinstance(v, str) else v for v in val]
           ^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/utils/module_loading.py", line 32, in import_string
    raise ImportError(
ImportError: Module "rest_framework.permissions" does not define a "IsAdmin" attribute/class
Internal Server Error: /auth/users/
Traceback (most recent call last):
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/utils/module_loading.py", line 16, in cached_import
    return getattr(module, class_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'rest_framework.permissions' has no attribute 'IsAdmin'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/rest_framework/views.py", line 331, in check_permissions
    for permission in self.get_permissions():
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/djoser/views.py", line 73, in get_permissions
    self.permission_classes = settings.PERMISSIONS.user_list
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/djoser/conf.py", line 22, in __getattribute__
    val = [import_string(v) if isinstance(v, str) else v for v in val]
           ^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/utils/module_loading.py", line 32, in import_string
    raise ImportError(
ImportError: Module "rest_framework.permissions" does not define a "IsAdmin" attribute/class
"GET /auth/users/ HTTP/1.1" 500 134429
"GET /auth/users/ HTTP/1.1" 500 134429
Internal Server Error: /auth/users/
Traceback (most recent call last):
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/utils/module_loading.py", line 16, in cached_import
    return getattr(module, class_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'rest_framework.permissions' has no attribute 'IsAdmin'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/rest_framework/views.py", line 331, in check_permissions
    for permission in self.get_permissions():
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/djoser/views.py", line 73, in get_permissions
    self.permission_classes = settings.PERMISSIONS.user_list
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/djoser/conf.py", line 22, in __getattribute__
    val = [import_string(v) if isinstance(v, str) else v for v in val]
           ^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/utils/module_loading.py", line 32, in import_string
    raise ImportError(
ImportError: Module "rest_framework.permissions" does not define a "IsAdmin" attribute/class
Internal Server Error: /auth/users/
Traceback (most recent call last):
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/utils/module_loading.py", line 16, in cached_import
    return getattr(module, class_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'rest_framework.permissions' has no attribute 'IsAdmin'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/rest_framework/views.py", line 331, in check_permissions
    for permission in self.get_permissions():
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/djoser/views.py", line 73, in get_permissions
    self.permission_classes = settings.PERMISSIONS.user_list
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/djoser/conf.py", line 22, in __getattribute__
    val = [import_string(v) if isinstance(v, str) else v for v in val]
           ^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/utils/module_loading.py", line 32, in import_string
    raise ImportError(
ImportError: Module "rest_framework.permissions" does not define a "IsAdmin" attribute/class
"GET /auth/users/ HTTP/1.1" 500 134430
"GET /auth/users/ HTTP/1.1" 500 134430
Internal Server Error: /auth/users/
Traceback (most recent call last):
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/utils/module_loading.py", line 16, in cached_import
    return getattr(module, class_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'rest_framework.permissions' has no attribute 'IsAdmin'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/rest_framework/views.py", line 331, in check_permissions
    for permission in self.get_permissions():
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/djoser/views.py", line 73, in get_permissions
    self.permission_classes = settings.PERMISSIONS.user_list
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/djoser/conf.py", line 22, in __getattribute__
    val = [import_string(v) if isinstance(v, str) else v for v in val]
           ^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/utils/module_loading.py", line 32, in import_string
    raise ImportError(
ImportError: Module "rest_framework.permissions" does not define a "IsAdmin" attribute/class
Internal Server Error: /auth/users/
Traceback (most recent call last):
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/utils/module_loading.py", line 16, in cached_import
    return getattr(module, class_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'rest_framework.permissions' has no attribute 'IsAdmin'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/rest_framework/views.py", line 331, in check_permissions
    for permission in self.get_permissions():
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/djoser/views.py", line 73, in get_permissions
    self.permission_classes = settings.PERMISSIONS.user_list
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/djoser/conf.py", line 22, in __getattribute__
    val = [import_string(v) if isinstance(v, str) else v for v in val]
           ^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/utils/module_loading.py", line 32, in import_string
    raise ImportError(
ImportError: Module "rest_framework.permissions" does not define a "IsAdmin" attribute/class
"GET /auth/users/ HTTP/1.1" 500 134429
"GET /auth/users/ HTTP/1.1" 500 134429
DEBUG - En-tête Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1OTY5OTE2LCJpYXQiOjE3NDUzNjUxMTYsImp0aSI6ImViOTBhYmJhNjg0ZTQ5OWI4MTc5ZTJkYjM4YzFiNDY2IiwidXNlcl9pZCI6MX0.UvlkWX10E0-ED0vZAkWhQ_39jimXJauOJylPyiAU9Hc
DEBUG - User authentifié: True
DEBUG - Type d'utilisateur: User
DEBUG - En-tête Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1OTY5OTE2LCJpYXQiOjE3NDUzNjUxMTYsImp0aSI6ImViOTBhYmJhNjg0ZTQ5OWI4MTc5ZTJkYjM4YzFiNDY2IiwidXNlcl9pZCI6MX0.UvlkWX10E0-ED0vZAkWhQ_39jimXJauOJylPyiAU9Hc
DEBUG - User authentifié: True
DEBUG - Type d'utilisateur: User
Internal Server Error: /api/annonces/2
Traceback (most recent call last):
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 122, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/middleware/common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dakitech/Documents/bayis imo/bayisimmo/venv/lib/python3.12/site-packages/django/middleware/common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via PATCH, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining PATCH data. Change your form to point to 127.0.0.1:8000/api/annonces/2/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
"PATCH /api/annonces/2 HTTP/1.1" 500 83154
